import 'dart:io';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import '../theme/gov_theme.dart';
import '../models/record_model.dart';
import '../services/staged_sync_service.dart';
import '../services/sms_anchor_service.dart';
import '../services/panchanama_pdf_service.dart';

/// Screen 12: Record Detail Screen (Officer & Supervisor)
/// Comprehensive evidentiary record audit view: optical metrics, cryptographic signatures,
/// SHA-256 recursive hash chain parameters, and Section 63 BSA legal admissibility proof.
class RecordDetailScreen extends StatefulWidget {
  final LocalRecordModel record;
  final File? capturedImageFile;

  const RecordDetailScreen({
    super.key,
    required this.record,
    this.capturedImageFile,
  });

  @override
  State<RecordDetailScreen> createState() => _RecordDetailScreenState();
}

class _RecordDetailScreenState extends State<RecordDetailScreen> {
  late LocalRecordModel _currentRecord;
  bool _isSyncing = false;
  File? _evidencePhoto;

  @override
  void initState() {
    super.initState();
    _currentRecord = widget.record;
    _loadEvidencePhoto();
  }

  Future<void> _loadEvidencePhoto() async {
    if (widget.capturedImageFile != null && widget.capturedImageFile!.existsSync()) {
      setState(() => _evidencePhoto = widget.capturedImageFile);
      return;
    }
    try {
      final dir = await getApplicationDocumentsDirectory();
      File f = File("${dir.path}/MHA_SEIZURE_${widget.record.testId}_WATERMARKED.png");
      if (await f.exists()) {
        setState(() => _evidencePhoto = f);
      }
    } catch (_) {}
  }

  Future<void> _triggerSync() async {
    setState(() => _isSyncing = true);
    final ok1 = await StagedSyncService.instance.syncStage1Metadata(_currentRecord);

    if (ok1) {
      setState(() {
        _currentRecord = _currentRecord.copyWith(isStage1Synced: 1);
      });
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("Metadata block anchored to MHA National Central Server."),
            backgroundColor: GovTheme.alertNegativeText,
          ),
        );
      }
    } else {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("Network offline. Encrypted record safely queued locally."),
            backgroundColor: GovTheme.alertInconclusiveText,
          ),
        );
      }
    }
    setState(() => _isSyncing = false);
  }

  Future<void> _resendSmsAnchor() async {
    final ok = await SmsAnchorService.instance.dispatchSmsAnchor(_currentRecord);
    if (ok) {
      setState(() {
        _currentRecord = _currentRecord.copyWith(isSmsWitnessed: 1);
      });
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("2G SMS Out-of-Band Witness Anchor dispatched via SIM!"),
            backgroundColor: GovTheme.alertNegativeText,
          ),
        );
      }
    }
  }

  void _showBsaCertificateDialog() {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: GovTheme.bgSurface,
        title: Row(
          children: const [
            Icon(Icons.description, color: GovTheme.primary),
            SizedBox(width: 8),
            Text("BSA §63 Certificate", style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
          ],
        ),
        content: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                "CERTIFICATE UNDER SECTION 63 OF BHARATIYA SAKSHYA ADHINIYAM, 2023",
                style: TextStyle(fontSize: 11, fontWeight: FontWeight.w900, color: GovTheme.ashokaNavy),
              ),
              const SizedBox(height: 8),
              Text(
                "I hereby certify that the electronic record with SHA-256 Digest ${_currentRecord.recordHash} "
                "was generated by apparatus DEV-001 under lawful operational control at "
                "${DateFormat('dd-MMM-yyyy HH:mm:ss').format(DateTime.fromMillisecondsSinceEpoch((_currentRecord.timestampUtc * 1000).toInt()))} UTC.\n\n"
                "The hash chain integrity is verified mathematically, and digital signatures were affixed by Officer ${_currentRecord.officerId}.",
                style: const TextStyle(fontSize: 12, height: 1.4),
              ),
              const SizedBox(height: 12),
              Container(
                padding: const EdgeInsets.all(8),
                color: GovTheme.bgBase,
                child: Text(
                  "Evidentiary Hash: ${_currentRecord.recordHash}\nPrev Link: ${_currentRecord.prevHash.substring(0, 16)}...\nHardware Sig: ${_currentRecord.deviceSigHex.substring(0, 24)}...",
                  style: const TextStyle(fontSize: 10, fontFamily: 'monospace'),
                ),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text("CLOSE"),
          ),
          ElevatedButton.icon(
            style: ElevatedButton.styleFrom(backgroundColor: GovTheme.primary),
            onPressed: () async {
              Navigator.pop(ctx);
              try {
                await PanchanamaPdfService.export(_currentRecord, evidencePhoto: _evidencePhoto);
              } catch (e) {
                if (!mounted) return;
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text("PDF export failed: $e"), backgroundColor: GovTheme.alertPositiveText),
                );
              }
            },
            icon: const Icon(Icons.download, size: 16, color: Colors.white),
            label: const Text("EXPORT PDF", style: TextStyle(color: Colors.white, fontSize: 12)),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GovTheme.bgBase,
      appBar: AppBar(
        title: Text(_currentRecord.testId),
        actions: [
          IconButton(
            icon: const Icon(Icons.picture_as_pdf, color: Colors.white),
            tooltip: "Export BSA §63 Certificate",
            onPressed: _showBsaCertificateDialog,
          ),
        ],
      ),
      body: SafeArea(
        child: Column(
          children: [
            const GovHeaderBanner(
              titleText: "MINISTRY OF HOME AFFAIRS",
              subtitleText: "STATUTORY EVIDENCE AUDIT • COURT-READY RECORD",
            ),
            const StatutoryWarningBanner(
              text: "Presumptive field result. Confirmatory laboratory gas chromatography mandated under NDPS §52A.",
            ),
            Expanded(
              child: ListView(
                padding: const EdgeInsets.all(GovTheme.space16),
                children: [
                  // Prominent Result Banner
                  GovResultBadge(
                    classification: _currentRecord.classification,
                    confidence: _currentRecord.confidence,
                    isLarge: true,
                  ),
                  const SizedBox(height: GovTheme.space16),

                  // Stamped Evidence Photograph
                  if (_evidencePhoto != null && _evidencePhoto!.existsSync()) ...[
                    Container(
                      width: double.infinity,
                      decoration: BoxDecoration(
                        color: Colors.black,
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(color: GovTheme.ashokaNavy, width: 2),
                      ),
                      clipBehavior: Clip.antiAlias,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          AspectRatio(
                            aspectRatio: 16 / 9,
                            child: Image.file(
                              _evidencePhoto!,
                              fit: BoxFit.cover,
                            ),
                          ),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                            color: GovTheme.ashokaNavy,
                            child: Row(
                              children: const [
                                Icon(Icons.verified, color: Colors.amberAccent, size: 16),
                                SizedBox(width: 8),
                                Expanded(
                                  child: Text(
                                    "EVIDENTIARY PHOTO: Live GPS & Statutory Banner Sealed",
                                    style: TextStyle(
                                      fontSize: 11.5,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.white,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: GovTheme.space16),
                  ],

                  // Field Test Evidence & Accuracy Card
                  Container(
                    padding: const EdgeInsets.all(GovTheme.space16),
                    decoration: BoxDecoration(
                      color: GovTheme.bgSurface,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: GovTheme.borderDefault),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          "FIELD TEST EVIDENCE & REAGENT ACCURACY",
                          style: TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: GovTheme.primary),
                        ),
                        const SizedBox(height: 10),
                        _buildRow("Substance Identified", _currentRecord.simpleDrugName),
                        _buildRow("Field Test Kit", _currentRecord.simpleKitDescription),
                        _buildRow(
                          "Color Match Accuracy",
                          "${_currentRecord.confidence.toStringAsFixed(1)}% Match (${_currentRecord.deltaE2000.toStringAsFixed(2)} ΔE - Pass)",
                        ),
                        _buildRow("Photo Focus Quality", "Sharp & In Focus (Variance >= 100)"),
                        _buildRow("Reaction Window", "${_currentRecord.reactionTimeSeconds}s (Kinetic Plateau Met)"),
                        _buildRow("Suspect Present at Scene", _currentRecord.accusedPresent ? "YES (Mandatory NDPS §52A)" : "NO"),
                        _buildRow("Reference Card Serial", _currentRecord.cardSerial),
                      ],
                    ),
                  ),
                  const SizedBox(height: GovTheme.space16),

                  // Spatial, Temporal & Officer Binding Card
                  Container(
                    padding: const EdgeInsets.all(GovTheme.space16),
                    decoration: BoxDecoration(
                      color: GovTheme.bgSurface,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: GovTheme.borderDefault),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          "LOCATION, TIME & OFFICER DETAILS",
                          style: TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: GovTheme.primary),
                        ),
                        const SizedBox(height: 10),
                        _buildRow("Date & Time", _currentRecord.formattedDate),
                        _buildRow("Seizing Officer ID", _currentRecord.officerId),
                        _buildRow("Apparatus Device ID", _currentRecord.deviceId),
                        _buildRow(
                          "GPS Crime Scene Anchor",
                          _currentRecord.simpleLocation,
                          isAlert: _currentRecord.latitude == null,
                        ),
                        _buildRow("Evidence Tamper Status", _currentRecord.simpleIntegrityStatus),
                        _buildRow("Central Server Sync", _currentRecord.simpleSyncStatus),
                      ],
                    ),
                  ),
                  const SizedBox(height: GovTheme.space16),

                  // Cryptographic Chain Hashes Card
                  Container(
                    padding: const EdgeInsets.all(GovTheme.space16),
                    decoration: BoxDecoration(
                      color: GovTheme.bgSurface,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: GovTheme.borderDefault),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          "CRYPTOGRAPHIC TAMPER-EVIDENT LEDGER",
                          style: TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: GovTheme.primary),
                        ),
                        const SizedBox(height: 10),
                        const Text("Current Block SHA-256 Digest:", style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                        SelectableText(
                          _currentRecord.recordHash,
                          style: const TextStyle(fontSize: 11, fontFamily: 'monospace', color: GovTheme.ashokaNavy),
                        ),
                        const SizedBox(height: 8),
                        const Text("Previous Block Hash (H_{n-1}):", style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                        SelectableText(
                          _currentRecord.prevHash,
                          style: const TextStyle(fontSize: 11, fontFamily: 'monospace', color: GovTheme.textSecondary),
                        ),
                        const SizedBox(height: 8),
                        const Text("Device Hardware P-256 Signature:", style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                        SelectableText(
                          _currentRecord.deviceSigHex,
                          style: const TextStyle(fontSize: 10, fontFamily: 'monospace', color: Colors.blueGrey),
                        ),
                        const SizedBox(height: 8),
                        const Text("Officer Ephemeral ECDSA Signature:", style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                        SelectableText(
                          _currentRecord.officerSigHex,
                          style: const TextStyle(fontSize: 10, fontFamily: 'monospace', color: Colors.blueGrey),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: GovTheme.space16),

                  // Out-of-Band & Staged Sync Card
                  Container(
                    padding: const EdgeInsets.all(GovTheme.space16),
                    decoration: BoxDecoration(
                      color: GovTheme.bgSurface,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: GovTheme.borderDefault),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          "SYNC MESH & OUT-OF-BAND ANCHOR",
                          style: TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: GovTheme.primary),
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              _currentRecord.isStage1Synced == 1 ? "Cloud Server Synced" : "Cloud Sync Pending",
                              style: TextStyle(
                                fontSize: 13,
                                fontWeight: FontWeight.bold,
                                color: _currentRecord.isStage1Synced == 1
                                    ? GovTheme.alertNegativeText
                                    : GovTheme.alertInconclusiveText,
                              ),
                            ),
                            ElevatedButton(
                              style: ElevatedButton.styleFrom(
                                backgroundColor: GovTheme.primary,
                                minimumSize: const Size(100, 36),
                              ),
                              onPressed: _isSyncing ? null : _triggerSync,
                              child: _isSyncing
                                  ? const SizedBox(width: 14, height: 14, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                                  : const Text("Sync Now", style: TextStyle(fontSize: 12, color: Colors.white)),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              _currentRecord.isSmsWitnessed == 1 ? "2G SMS Witness Dispatched" : "2G SMS Witness Pending",
                              style: TextStyle(
                                fontSize: 13,
                                fontWeight: FontWeight.bold,
                                color: _currentRecord.isSmsWitnessed == 1
                                    ? GovTheme.alertNegativeText
                                    : GovTheme.alertInconclusiveText,
                              ),
                            ),
                            OutlinedButton(
                              style: OutlinedButton.styleFrom(
                                minimumSize: const Size(100, 36),
                              ),
                              onPressed: _resendSmsAnchor,
                              child: const Text("Send SMS", style: TextStyle(fontSize: 12)),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildRow(String label, String value, {bool isAlert = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 5.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            flex: 4,
            child: Text(
              label,
              style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w600, color: GovTheme.textSecondary),
            ),
          ),
          const SizedBox(width: 10),
          Expanded(
            flex: 5,
            child: Text(
              value,
              textAlign: TextAlign.right,
              style: TextStyle(
                fontSize: 14.5,
                fontWeight: FontWeight.bold,
                color: isAlert ? GovTheme.alertPositiveText : GovTheme.textPrimary,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
